/**
 * Dealer script for the five bespoke cards (issue #4).
 *
 * Workflow: `bun run deal:<slug>` (or `deal:all`) shuffles a fresh card for a
 * player, prints it as a 5x5 grid to eyeball, and rewrites that player's entry
 * in `ts/partials/_cards.ts` — leaving the other four untouched. Deal, look,
 * deal again until happy, then commit. The commit is the lock.
 *
 * The deal itself lives in the shared `dealGrid` (`ts/partials/_deal.ts`), the
 * same logic the seeded public path (#12) reuses; here we just feed it a random
 * `rng` and the "special" audience. Center distinctness across the five is this
 * script's job (dealGrid only picks from the centers it is handed).
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import chalk from "chalk";
import Table from "cli-table3";

import { squares, centers, essentials } from "../ts/partials/_squares.js";
import type { BingoSquare } from "../ts/partials/_squares.js";
import { dealGrid, CENTER_INDEX } from "../ts/partials/_deal.js";
import committedCards from "../ts/partials/_cards.js";
import type { PlayerCard } from "../ts/partials/_cards.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const cardsPath = path.resolve(__dirname, "..", "ts", "partials", "_cards.ts");

/** Canonical roster: the source of truth for who exists and their display name. */
const ROSTER: { slug: string; name: string }[] = [
  { slug: "lemon", name: "Lemon" },
  { slug: "simone", name: "Simone" },
  { slug: "angie", name: "Angie" },
  { slug: "mike", name: "Mike" },
  { slug: "victor", name: "Victor" },
];

/**
 * Canonical text of `_cards.ts` above the data. Kept here because this script
 * regenerates the file; if `PlayerCard` changes, update this to match.
 */
const MODULE_HEADER = `/**
 * Committed bespoke cards for the five special players.
 *
 * Everything below the \`PlayerCard\` interface is regenerated by the dealer
 * script (issue #4, \`scripts/deal.ts\`) — re-deal with \`bun run deal:<slug>\` or
 * \`bun run deal:all\`, review, then commit. The commit is the lock. The keys of
 * this object are the canonical list of special names that \`resolveCard()\`
 * recognises.
 */

export interface PlayerCard {
  slug: string;
  name: string;
  /**
   * 25 dealt square IDs in grid order (row-major 5x5); index 12 is the
   * player-marked center (a \`C\`-prefixed id). Empty until a deal is committed.
   */
  squareIds: string[];
}
`;

/**
 * Serialize one card entry as prettier would format it: an empty card stays on
 * one line; a dealt (25-id) card expands, since the array overflows the print
 * width. Emitting the canonical shape keeps a later editor-format a no-op.
 */
function serializeCard(card: PlayerCard): string {
  const head = `  ${card.slug}: { slug: "${card.slug}", name: "${card.name}"`;
  if (card.squareIds.length === 0) {
    return `${head}, squareIds: [] },`;
  }
  const ids = card.squareIds.map((id) => `      "${id}",`).join("\n");
  return [
    `  ${card.slug}: {`,
    `    slug: "${card.slug}",`,
    `    name: "${card.name}",`,
    `    squareIds: [`,
    ids,
    `    ],`,
    `  },`,
  ].join("\n");
}

/** Regenerate the whole `_cards.ts` file text from a roster-ordered card map. */
export function renderCardsModule(cards: Record<string, PlayerCard>): string {
  const entries = ROSTER.map(({ slug }) => serializeCard(cards[slug])).join(
    "\n",
  );
  return `${MODULE_HEADER}
export const cards: Record<string, PlayerCard> = {
${entries}
};

export default cards;
`;
}

/** Every square from every group, indexed by id, for the terminal render. */
const squareById = new Map<string, BingoSquare>(
  [...squares, ...centers, ...essentials.flatMap((g) => g.squares)].map((s) => [
    s.id,
    s,
  ]),
);

const CELL_WIDTH = 22; // column width incl. cli-table3's 1-space padding each side

/** Color a cell's label by its role: center, `see`, `do`, or a missing id. */
function paintCell(id: string, index: number): string {
  const square = squareById.get(id);
  const label = square ? (square.shortText ?? square.text) : `?${id}`;
  if (index === CENTER_INDEX) return chalk.magenta.bold(label.toUpperCase());
  if (!square) return chalk.red(label);
  return square.type === "do" ? chalk.cyan(label) : chalk.green(label);
}

/** Print a dealt card as a 5x5 grid so a deal can be judged without a browser. */
function renderGrid(name: string, squareIds: string[]): void {
  const table = new Table({
    colWidths: Array(5).fill(CELL_WIDTH),
    colAligns: Array(5).fill("center"),
    wordWrap: true,
    style: { head: [], border: ["grey"] },
  });

  for (let row = 0; row < 5; row++) {
    table.push(
      squareIds
        .slice(row * 5, row * 5 + 5)
        .map((id, col) => paintCell(id, row * 5 + col)),
    );
  }

  console.log(`\n${chalk.bold.underline(name)}`);
  console.log(table.toString());
}

/** One-line key for the grid colors, printed once per run. */
function printLegend(): void {
  console.log(
    chalk.dim("key  ") +
      chalk.green("■ see") +
      chalk.dim("   ") +
      chalk.cyan("■ do") +
      chalk.dim("   ") +
      chalk.magenta.bold("CENTER") +
      chalk.dim(" (player-marked)"),
  );
}

function usageAndExit(): never {
  const slugs = ROSTER.map((r) => r.slug).join(", ");
  console.error(
    chalk.red("Usage: bun scripts/deal.ts <slug|all>") +
      `\n  valid slugs: ${slugs}, or "all"`,
  );
  process.exit(1);
}

function main(): void {
  const target = process.argv[2];
  if (!target) usageAndExit();

  const isAll = target === "all";
  if (!isAll && !ROSTER.some((r) => r.slug === target)) usageAndExit();

  const targets = isAll ? ROSTER.map((r) => r.slug) : [target];

  // Start from what is committed so the players we do not re-deal are preserved.
  const result: Record<string, PlayerCard> = {};
  for (const { slug, name } of ROSTER) {
    result[slug] = {
      slug,
      name,
      squareIds: committedCards[slug]?.squareIds ?? [],
    };
  }

  // Prefer a center no other card already uses, so the five stay distinct.
  const usedCenters = new Set<string>();
  if (!isAll) {
    for (const { slug } of ROSTER) {
      if (slug === target) continue;
      const committedCenter = result[slug].squareIds[CENTER_INDEX];
      if (committedCenter) usedCenters.add(committedCenter);
    }
  }

  printLegend();

  for (const slug of targets) {
    const availableCenters = centers.filter((c) => !usedCenters.has(c.id));
    const grid = dealGrid({
      pool: squares,
      centers: availableCenters.length > 0 ? availableCenters : centers,
      essentials,
      audience: "special",
      rng: Math.random,
    });
    result[slug].squareIds = grid;
    usedCenters.add(grid[CENTER_INDEX]);
    renderGrid(result[slug].name, grid);
  }

  fs.writeFileSync(cardsPath, renderCardsModule(result));

  const dealt = targets.join(", ");
  console.log(
    chalk.green(`\n✓ Dealt ${dealt} → ts/partials/_cards.ts`) +
      chalk.dim(
        "\n  review, run `bun run build`, then commit to lock it in.\n",
      ),
  );
}

main();
