/**
 * The shared pool of bingo squares.
 * All five cards draw from this one pool, so cards differ but overlap.
 * See _docs/writing-style.md for the authoring rules. Pool ids are prefixed `P`
 * and kept contiguous (`P1`..`Pn`, matching array order), so deleting a square
 * renumbers everything after it. Ids are positional bookkeeping, not identity:
 * nothing outside the repo persists them, since a deploy invalidates saved
 * marks. `_cards.ts` does reference them, so renumber both together.
 */

import type { BingoSquare } from "./_types.js";

export const squares: BingoSquare[] = [
  {
    id: "P1",
    text: "I watched somebody drink four or more glasses at the all-you-can-drink milk booth. If nobody else was going to, that somebody was me.",
    shortText: "Four glasses of milk",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P2",
    text: "I saw a nearly empty bucket of Sweet Martha's in the hands of someone sick with regret.",
    shortText: "A bucket of Sweet Martha's regret",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P3",
    text: "I found a grown adult fast asleep sitting bolt upright on a bench.",
    shortText: "Asleep bolt upright on a bench",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P4",
    text: "I handed a cheese curd to a stranger and told them it was the sacrament of the fair.",
    shortText: "Cheese curd sacrament",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P5",
    text: "I spotted someone wearing two or more camo pattern clothing items (2 socks is 1 item).",
    shortText: "2+ camo items",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P6",
    text: "I ate a full bag of Tom Thumb mini donuts before noon.",
    shortText: "A bag of mini donuts before noon",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P7",
    text: "I watched an animal actually get born in the Miracle of Birth Center.",
    shortText: "Saw a live birth at the barn",
    rarity: "rare",
    type: "see",
  },
  {
    id: "P8",
    text: "I saw a toddler with a mullet he never agreed to.",
    shortText: "A toddler with a mullet",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P9",
    text: "I saw someone with obvious corn cob butter on their wrist (telling them about it was optional).",
    shortText: "There's butter on your wrist, brah!",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P10",
    text: "I stepped around a fresh pile of horse shit nobody had cleaned up yet.",
    shortText: "A fresh pile of horse shit",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P11",
    text: "I saw a man in overalls with no shirt underneath.",
    shortText: "Overalls, no shirt",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P12",
    text: "I saw someone cooling off with a right-wing campaign hand fan.",
    shortText: "A right-wing hand fan",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P13",
    text: "I saw a sunburn peeling in real time.",
    shortText: "A peeling sunburn",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P14",
    text: "I saw two farm boys sharing a cigarette.",
    shortText: "Farm boys sharing a smoke",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P15",
    text: "I saw a kid on a leash.",
    shortText: "A kid on a leash",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P16",
    text: "I saw socks worn with sandals.",
    shortText: "Socks with sandals",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P17",
    text: "I saw someone crying while holding an ice cream cone.",
    shortText: "Crying with an ice cream cone",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P18",
    text: "I saw a carnie wearing at least one piece of gold jewelry.",
    shortText: "A carnie in gold jewelry",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P19",
    text: "I saw a full-size shirt that a belly had turned into an accidental crop top.",
    shortText: "Belly vanquishes shirt",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P20",
    text: "I ordered a 'corn dog' at a Pronto Pup stand and refused to be corrected.",
    shortText: "Ordered a 'corn dog' at Pronto Pup",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P21",
    text: "I yelled 'I can't believe it!' during an as-seen-on-TV gadget demo.",
    shortText: "Heckled a demo",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P22",
    text: "I saw at least three grown men gathered around a single tractor.",
    shortText: "3+ men around one tractor",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P23",
    text: "I saw someone hauling a Midway prize bigger than the child who won it.",
    shortText: "Midway prize bigger than the kid",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P24",
    text: "I watched a Butter Princess getting her likeness etched into butter.",
    shortText: "A live butter carving",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P25",
    text: "I spotted a Butter Princess outside of the Dairy Building in her sash and tiara.",
    shortText: "A Butter Princess in the wild",
    rarity: "rare",
    type: "see",
  },
  {
    id: "P26",
    text: "I ate a deep-fried candy bar just to learn how disappointing life can be.",
    shortText: "Deep-fried candy bar",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P27",
    text: "I rode the Giant Slide with my arms crossed and a serious expression.",
    shortText: "Stone-faced on the Giant Slide",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P28",
    text: "I pointed at a hog I was certain weighed more than 270 pounds (the Big Boar is over 1,000 pounds and does not count).",
    shortText: "A hog over 270 lbs (not the Big Boar)",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P29",
    text: "I spent at least 6 Fun Card tickets on the same 'skill' game and won nothing at all. Any prize, consolation prizes included, forfeits the square.",
    shortText: "6+ tickets, no prize",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P30",
    text: "I let this year's new-foods list pick one at random, then tracked it down in person (I did not have to eat it).",
    shortText: "Found new food",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P31",
    text: "I held up one beer from a Brewers Guild flight and described its 'notes' for a solid minute.",
    shortText: "Brewers Guild beer 'notes'",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P32",
    text: "I watched somebody stop dead in the middle of the street and get walked into from behind. They had it coming.",
    shortText: "Rear-ended on foot",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P33",
    text: "I stood in a misting station, in full view of my group, until one of them finally asked me to move.",
    shortText: "Made to leave the misting station",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P34",
    text: "While riding the Skyride, I looked at the single cable holding us aloft and whispered 'it's gonna be fine'.",
    shortText: "Feeling nervous on the Skyride",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P35",
    text: "I found a scarecrow in the Ag Building that made its political opinions perfectly clear.",
    shortText: "Nakedly political scarecrow",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P36",
    text: "I played a coin-pusher machine and actually walked away with tickets.",
    shortText: "Won tickets on the coin pusher",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P37",
    text: "For a brief moment, I was the loudest singer at the Great Minnesota Sing-Along.",
    shortText: "Loudest at the Sing-Along",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P38",
    text: "I spotted an actual Fairchild (the gopher mascot) in the wild.",
    shortText: "Fairchild in the wild",
    rarity: "rare",
    type: "see",
  },
  {
    id: "P39",
    text: "I found a fish at the DNR fish pond with a chunk bitten out of it.",
    shortText: "Bitten fish at the DNR pond",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P40",
    text: "I saw someone carrying a bag of cotton candy bigger than their own head.",
    shortText: "Cotton candy bigger than a head",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P41",
    text: "I took a yardstick because it was free, even though I knew I had no use for it and I'd have to carry it the rest of the day.",
    shortText: "Took a free yardstick",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P42",
    text: "I ordered a thing of fries and used malt vinegar as my only condiment. I did not get any ketchup.",
    shortText: "Fries w/ vinegar",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P43",
    text: "I correctly identified the queen in a live honeybee display (with someone's help if needed).",
    shortText: "Found the queen bee",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P44",
    text: "I saw someone eating something on a stick that used to be part of an alligator.",
    shortText: "Alligator on a stick",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P45",
    text: "I found a pumpkin that weighs more than 1,000 pounds.",
    shortText: "A 1,000+ lb pumpkin",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P46",
    text: "I saw a family of three or more people all wearing matching t-shirts.",
    shortText: "3+ people in matching shirts",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P47",
    text: "I saw a blue first-place ribbon on an entry I could not tell apart from the ones that lost.",
    shortText: "A baffling blue ribbon",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P48",
    text: "I spun a prize wheel and kept the prize, which I did not want and could not use.",
    shortText: "Spun a prize wheel",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P49",
    text: "I saw a hot tub for sale with a price tag over $10,000.",
    shortText: "A $10,000+ hot tub",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P50",
    text: "I saw a goth kid in head-to-toe black, standing in the direct sun.",
    shortText: "A goth kid in all black",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P51",
    text: "I saw two people exit Ye Old Mill in complete silence.",
    shortText: "Silence at Ye Old Mill",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P52",
    text: "I saw someone wearing cargo shorts and a fanny pack. I say that not to mock. I say that because I feel self-conscious about how many pockets I have.",
    shortText: "Cargo shorts + fanny pack",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P53",
    text: "I saw someone with henna running all the way down an entire arm or leg.",
    shortText: "Way too much henna",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P54",
    text: "I saw something in one of the toilet stalls and... I don't want to talk about it. Just let me have this square and don't ask any questions, okay?",
    shortText: "A TOILET HORROR!",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P55",
    text: "I saw two people the GOP is always complaining about kiss for a photo op in front of the GOP building.",
    shortText: "A photo-op kiss at the GOP building",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P56",
    text: "I passed by the Libertarian booth twice and saw the same three guys.",
    shortText: "The same three Libertarians",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P57",
    text: "I ate walleye on a stick, the single most Minnesotan sentence I have ever said.",
    shortText: "Walleye on a stick",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P58",
    text: "I saw a parent carrying their kid while pushing a completely empty stroller.",
    shortText: "Empty stroller, kid in arms",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P59",
    text: "I watched somebody dart across the parade route behind a float rather than wait for the parade to end.",
    shortText: "Jaywalked the parade",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P60",
    text: "I looked at one of the award-winning photos in the Fine Arts building. It was... Fine. It was a perfectly nice photo, I guess.",
    shortText: "A perfectly fine Fine Arts photo",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P61",
    text: "I pet a horse, but only after asking someone's permission.",
    shortText: "Pet A Horse",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P62",
    text: "I watched live polka music. How do I know it was polka? There was an accordion. That qualifies.",
    shortText: "Live Polka",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P63",
    text: "I sat in the driver's seat of a combine harvester that costs more than my house.",
    shortText: "Sat On Combine",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P64",
    text: "I found a chicken that has a breed more than 14 letters long.",
    shortText: "Complicated Chicken Breed",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P65",
    text: "I found a cow from Otter Tail.",
    shortText: "Otter Tail Cow",
    rarity: "rare",
    type: "see",
  },
  {
    id: "P66",
    text: "In the Eco building, I collected 2 Eco Bingo stamps. Then I threw the card in the recycling bin.",
    shortText: "Eco Bingo",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P67",
    text: "I saw a shark tooth necklace at the International Bazaar. Whether or not I bought it has nothing to do with BINGOPE.",
    shortText: "Shark Tooth Necklace",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P68",
    text: "I saw a jar of pickled watermelon rind on display in the Creative Activities building.",
    shortText: "Pickled Watermelon",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P69",
    text: "I ate an entire foot-long hot dog in six bites or fewer.",
    shortText: "Foot-Long, 6 Bites",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P70",
    text: "I watched a karaoke singer stop even trying, and the backing vocals carried the rest of the song alone.",
    shortText: "Karaoke Surrender",
    rarity: "rare",
    type: "see",
  },
  {
    id: "P71",
    text: "A vendor offered me a free item if I signed up for their mailing list, so I wrote down 'hogdaddy1987@hotmail.com'.",
    shortText: "hogdaddy1987@hotmail.com",
    rarity: "medium",
    type: "do",
  },
  {
    id: "P72",
    text: "I asked someone working at the History & Heritage Center how to get to the Minnesota State Fair. I am not allowed to mark this square if I laughed while asking.",
    shortText: "Directions To The Fair",
    rarity: "gimme",
    type: "do",
  },
  {
    id: "P73",
    text: "I saw a sheep wearing a white cloak and a pointed white hood, and now I'll live with unanswered questions about that sheep's views on race.",
    shortText: "Klan Sheep",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P74",
    text: "I watched a kid too young to drive absolutely manhandle an animal that would win a fight against me.",
    shortText: "Small Kid, Big Animal",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P75",
    text: "I witnessed the death of a balloon.",
    shortText: "Death Of A Balloon",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P76",
    text: "I saw someone wearing a garbage bag as a raincoat.",
    shortText: "Garbage Bag Poncho",
    rarity: "rare",
    type: "see",
  },
  {
    id: "P77",
    text: "I found a slice of pizza that costs $8 or more.",
    shortText: "$8+ Pizza",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P78",
    text: "I found a bug painted onto dishware, on purpose, by hand.",
    shortText: "A Bug Painted On Dishware",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P79",
    text: "I found a crocheted fruit with a face and limbs. The fair's rules specify that it may not be made out of actual fruit.",
    shortText: "The Crochet Fruit Doll",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P80",
    text: "I walked through somebody else's vape cloud.",
    shortText: "Vape Cloud",
    rarity: "gimme",
    type: "see",
  },
  {
    id: "P81",
    text: "I saw someone filming in vertical, with narration, while standing in the middle of the walkway. Whether or not I slapped that person is unrelated to the game.",
    shortText: "TikTok Fail",
    rarity: "medium",
    type: "see",
  },
  {
    id: "P82",
    text: "I saw a grown adult with a blue mouth.",
    shortText: "A grown adult, blue mouth",
    rarity: "medium",
    type: "see",
  },
];
